import type { Listing } from '@/types'

export const MOCK_LISTINGS: Listing[] = [
  {
    id: '1',
    host_id: 'host1',
    category: 'mirrorless',
    brand: 'Sony',
    model: 'A7 IV',
    title: 'Sony A7 IV Full-Frame Mirrorless Camera',
    description: 'Perfect for professional photography and videography.',
    condition: 'excellent',
    daily_price: 2500,
    weekly_price: 15000,
    monthly_price: 50000,
    security_deposit: 10000,
    city: 'Manila',
    province: 'Metro Manila',
    is_instant_book: true,
    is_active: true,
    rating: 4.98,
    review_count: 124,
    images: ['https://images.unsplash.com/photo-1621155346337-1d19476ba7d6?w=800&q=80'],
    accessories: ['Battery x2', 'Charger', 'Strap', 'Body Cap'],
    created_at: '2024-01-01',
    host: { id: 'host1', full_name: 'Mark Reyes', avatar_url: null, is_verified: true, is_host: true, host_rating: 4.9, host_review_count: 89, response_time_hours: 1, created_at: '2023-01-01' },
  },
  {
    id: '2',
    host_id: 'host2',
    category: 'mirrorless',
    brand: 'Canon',
    model: 'EOS R6 Mark II',
    title: 'Canon EOS R6 Mark II Mirrorless Camera',
    description: 'Excellent for sports and wildlife photography.',
    condition: 'mint',
    daily_price: 2200,
    weekly_price: 13000,
    monthly_price: 45000,
    security_deposit: 9000,
    city: 'Makati',
    province: 'Metro Manila',
    is_instant_book: false,
    is_active: true,
    rating: 4.95,
    review_count: 67,
    images: ['https://images.unsplash.com/photo-1502920917128-1aa500764cbd?w=800&q=80'],
    accessories: ['Battery', 'Charger', 'USB-C Cable'],
    created_at: '2024-01-02',
    host: { id: 'host2', full_name: 'Anna Cruz', avatar_url: null, is_verified: true, is_host: true, host_rating: 5.0, host_review_count: 42, response_time_hours: 2, created_at: '2023-06-01' },
  },
  {
    id: '3',
    host_id: 'host3',
    category: 'smartphone',
    brand: 'Apple',
    model: 'iPhone 16 Pro Max',
    title: 'iPhone 16 Pro Max — 512GB',
    description: 'Top-of-the-line iPhone with ProRAW, 4K120 video.',
    condition: 'mint',
    daily_price: 1200,
    weekly_price: 7000,
    monthly_price: 24000,
    security_deposit: 5000,
    city: 'BGC',
    province: 'Metro Manila',
    is_instant_book: true,
    is_active: true,
    rating: 5.0,
    review_count: 38,
    images: ['https://images.unsplash.com/photo-1510557880182-3d4d3cba35a5?w=800&q=80'],
    accessories: ['Lightning Cable', 'Adapter', 'Case'],
    created_at: '2024-01-03',
    host: { id: 'host3', full_name: 'Carlo Santos', avatar_url: null, is_verified: true, is_host: true, host_rating: 4.8, host_review_count: 31, response_time_hours: 3, created_at: '2023-09-01' },
  },
  {
    id: '4',
    host_id: 'host4',
    category: 'lens',
    brand: 'Sony',
    model: 'FE 24-70mm f/2.8 GM II',
    title: 'Sony FE 24-70mm f/2.8 GM II Lens',
    description: 'Professional standard zoom lens, tack-sharp across the frame.',
    condition: 'excellent',
    daily_price: 1800,
    weekly_price: 10000,
    monthly_price: 35000,
    security_deposit: 8000,
    city: 'Quezon City',
    province: 'Metro Manila',
    is_instant_book: true,
    is_active: true,
    rating: 4.97,
    review_count: 55,
    images: ['https://images.unsplash.com/photo-1606986628253-40f985af3ef3?w=800&q=80'],
    accessories: ['Front Cap', 'Rear Cap', 'Hood', 'Pouch'],
    created_at: '2024-01-04',
    host: { id: 'host4', full_name: 'Lea Villanueva', avatar_url: null, is_verified: false, is_host: true, host_rating: 4.7, host_review_count: 28, response_time_hours: 4, created_at: '2023-07-01' },
  },
  {
    id: '5',
    host_id: 'host5',
    category: 'cinema',
    brand: 'Sony',
    model: 'FX3',
    title: 'Sony FX3 Cinema Line Camera',
    description: 'Full-frame cinema camera with S-Cinetone and 4K 120fps.',
    condition: 'excellent',
    daily_price: 4500,
    weekly_price: 27000,
    monthly_price: 90000,
    security_deposit: 20000,
    city: 'Pasig',
    province: 'Metro Manila',
    is_instant_book: false,
    is_active: true,
    rating: 4.93,
    review_count: 19,
    images: ['https://images.unsplash.com/photo-1616161560417-66d4db5892ec?w=800&q=80'],
    accessories: ['Battery x2', 'XLR Adapter', 'USB-C Cable'],
    created_at: '2024-01-05',
    host: { id: 'host5', full_name: 'Ryan Lim', avatar_url: null, is_verified: true, is_host: true, host_rating: 4.9, host_review_count: 15, response_time_hours: 2, created_at: '2023-05-01' },
  },
  {
    id: '6',
    host_id: 'host6',
    category: 'smartphone',
    brand: 'Samsung',
    model: 'Galaxy S25 Ultra',
    title: 'Samsung Galaxy S25 Ultra — 256GB',
    description: '200MP camera, S Pen, 8K video recording.',
    condition: 'mint',
    daily_price: 1000,
    weekly_price: 6000,
    monthly_price: 20000,
    security_deposit: 4500,
    city: 'Cebu City',
    province: 'Cebu',
    is_instant_book: true,
    is_active: true,
    rating: 4.88,
    review_count: 22,
    images: ['https://images.unsplash.com/photo-1610945265064-0e34e5519bbf?w=800&q=80'],
    accessories: ['USB-C Cable', 'S Pen', 'Case'],
    created_at: '2024-01-06',
    host: { id: 'host6', full_name: 'Grace Tan', avatar_url: null, is_verified: true, is_host: true, host_rating: 4.8, host_review_count: 17, response_time_hours: 1, created_at: '2023-10-01' },
  },
]

export const MOCK_BUNDLES = [
  {
    id: 'b1',
    title: 'Vlogging Kit',
    items: ['Sony ZV-E10', 'Wireless Microphone', 'Tripod', 'LED Light'],
    daily_price: 1800,
    image: 'https://images.unsplash.com/photo-1598300042247-d088f8ab3a91?w=800&q=80',
  },
  {
    id: 'b2',
    title: 'Wedding Photography Kit',
    items: ['Sony A7 IV', '85mm f/1.4 Lens', 'Flash x2', 'Extra Batteries'],
    daily_price: 5500,
    image: 'https://images.unsplash.com/photo-1606216794074-735e91aa2c92?w=800&q=80',
  },
  {
    id: 'b3',
    title: 'Travel Content Kit',
    items: ['Fujifilm X100VI', 'ND Filter Set', 'Gorilla Pod', 'Memory Cards'],
    daily_price: 2200,
    image: 'https://images.unsplash.com/photo-1452780212461-392a8d0cfe86?w=800&q=80',
  },
]
