import type { Listing } from '@/types'

export const MOCK_LISTINGS: Listing[] = [
  {
    id: '1',
    host_id: 'host1',
    category: 'mirrorless',
    brand: 'Sony',
    model: 'A7 IV',
    title: 'Sony A7 IV Full-Frame Mirrorless Camera',
    description: 'Perfect for professional photography and videography.',
    condition: 'excellent',
    daily_price: 2500,
    weekly_price: 15000,
    monthly_price: 50000,
    security_deposit: 10000,
    delivery_fee: null,
    city: 'Manila',
    province: 'Metro Manila',
    is_instant_book: true,
    is_active: true,
    is_draft: false,
    rating: 4.98,
    review_count: 124, view_count: 0,
    images: ['https://images.unsplash.com/photo-1692030180082-c468ed11a108?w=800&q=80', 'https://images.unsplash.com/photo-1697311622332-184b7bb19a46?w=800&q=80', 'https://images.unsplash.com/photo-1581591546349-f29007542ed4?w=800&q=80'],
    accessories: ['Battery x2', 'Charger', 'Strap', 'Body Cap'],
    created_at: '2024-01-01',
    host: { id: 'host1', full_name: 'Mark Reyes', avatar_url: null, qr_payment_url: null, qr_payment_label: null, is_verified: true, is_host: true, host_rating: 4.9, host_review_count: 89, response_time_hours: 1, bio: null, city: null, notify_new_booking: true, notify_messages: true, notify_reminders: true, notify_promos: false, created_at: '2023-01-01' },
  },
  {
    id: '2',
    host_id: 'host2',
    category: 'mirrorless',
    brand: 'Canon',
    model: 'EOS R6 Mark II',
    title: 'Canon EOS R6 Mark II Mirrorless Camera',
    description: 'Excellent for sports and wildlife photography.',
    condition: 'mint',
    daily_price: 2200,
    weekly_price: 13000,
    monthly_price: 45000,
    security_deposit: 9000,
    delivery_fee: null,
    city: 'Makati',
    province: 'Metro Manila',
    is_instant_book: false,
    is_active: true,
    is_draft: false,
    rating: 4.95,
    review_count: 67, view_count: 0,
    images: ['https://images.unsplash.com/photo-1613483187285-e84c582608f9?w=800&q=80', 'https://images.unsplash.com/photo-1613483187433-8c40c50ed660?w=800&q=80'],
    accessories: ['Battery', 'Charger', 'USB-C Cable'],
    created_at: '2024-01-02',
    host: { id: 'host2', full_name: 'Anna Cruz', avatar_url: null, qr_payment_url: null, qr_payment_label: null, is_verified: true, is_host: true, host_rating: 5.0, host_review_count: 42, response_time_hours: 2, bio: null, city: null, notify_new_booking: true, notify_messages: true, notify_reminders: true, notify_promos: false, created_at: '2023-06-01' },
  },
  {
    id: '3',
    host_id: 'host3',
    category: 'smartphone',
    brand: 'Apple',
    model: 'iPhone 16 Pro Max',
    title: 'iPhone 16 Pro Max — 512GB',
    description: 'Top-of-the-line iPhone with ProRAW, 4K120 video.',
    condition: 'mint',
    daily_price: 1200,
    weekly_price: 7000,
    monthly_price: 24000,
    security_deposit: 5000,
    delivery_fee: null,
    city: 'BGC',
    province: 'Metro Manila',
    is_instant_book: true,
    is_active: true,
    is_draft: false,
    rating: 5.0,
    review_count: 38, view_count: 0,
    images: ['https://images.unsplash.com/photo-1695619575474-9b45e37bc1e6?w=800&q=80', 'https://images.unsplash.com/photo-1695822958645-b2b058159215?w=800&q=80'],
    accessories: ['Lightning Cable', 'Adapter', 'Case'],
    created_at: '2024-01-03',
    host: { id: 'host3', full_name: 'Carlo Santos', avatar_url: null, qr_payment_url: null, qr_payment_label: null, is_verified: true, is_host: true, host_rating: 4.8, host_review_count: 31, response_time_hours: 3, bio: null, city: null, notify_new_booking: true, notify_messages: true, notify_reminders: true, notify_promos: false, created_at: '2023-09-01' },
  },
  {
    id: '4',
    host_id: 'host4',
    category: 'lens',
    brand: 'Sony',
    model: 'FE 24-70mm f/2.8 GM II',
    title: 'Sony FE 24-70mm f/2.8 GM II Lens',
    description: 'Professional standard zoom lens, tack-sharp across the frame.',
    condition: 'excellent',
    daily_price: 1800,
    weekly_price: 10000,
    monthly_price: 35000,
    security_deposit: 8000,
    delivery_fee: null,
    city: 'Quezon City',
    province: 'Metro Manila',
    is_instant_book: true,
    is_active: true,
    is_draft: false,
    rating: 4.97,
    review_count: 55, view_count: 0,
    images: ['https://images.unsplash.com/photo-1617005082133-548c4dd27f35?w=800&q=80'],
    accessories: ['Front Cap', 'Rear Cap', 'Hood', 'Pouch'],
    created_at: '2024-01-04',
    host: { id: 'host4', full_name: 'Lea Villanueva', avatar_url: null, qr_payment_url: null, qr_payment_label: null, is_verified: false, is_host: true, host_rating: 4.7, host_review_count: 28, response_time_hours: 4, bio: null, city: null, notify_new_booking: true, notify_messages: true, notify_reminders: true, notify_promos: false, created_at: '2023-07-01' },
  },
  {
    id: '5',
    host_id: 'host5',
    category: 'cinema',
    brand: 'Sony',
    model: 'FX3',
    title: 'Sony FX3 Cinema Line Camera',
    description: 'Full-frame cinema camera with S-Cinetone and 4K 120fps.',
    condition: 'excellent',
    daily_price: 4500,
    weekly_price: 27000,
    monthly_price: 90000,
    security_deposit: 20000,
    delivery_fee: null,
    city: 'Pasig',
    province: 'Metro Manila',
    is_instant_book: false,
    is_active: true,
    is_draft: false,
    rating: 4.93,
    review_count: 19, view_count: 0,
    images: ['https://images.unsplash.com/photo-1743815888957-5be0bc9da851?w=800&q=80'],
    accessories: ['Battery x2', 'XLR Adapter', 'USB-C Cable'],
    created_at: '2024-01-05',
    host: { id: 'host5', full_name: 'Ryan Lim', avatar_url: null, qr_payment_url: null, qr_payment_label: null, is_verified: true, is_host: true, host_rating: 4.9, host_review_count: 15, response_time_hours: 2, bio: null, city: null, notify_new_booking: true, notify_messages: true, notify_reminders: true, notify_promos: false, created_at: '2023-05-01' },
  },
  {
    id: '6',
    host_id: 'host6',
    category: 'smartphone',
    brand: 'Samsung',
    model: 'Galaxy S25 Ultra',
    title: 'Samsung Galaxy S25 Ultra — 256GB',
    description: '200MP camera, S Pen, 8K video recording.',
    condition: 'mint',
    daily_price: 1000,
    weekly_price: 6000,
    monthly_price: 20000,
    security_deposit: 4500,
    delivery_fee: null,
    city: 'Cebu City',
    province: 'Cebu',
    is_instant_book: true,
    is_active: true,
    is_draft: false,
    rating: 4.88,
    review_count: 22, view_count: 0,
    images: ['https://images.unsplash.com/photo-1738830234395-a351829a1c7b?w=800&q=80'],
    accessories: ['USB-C Cable', 'S Pen', 'Case'],
    created_at: '2024-01-06',
    host: { id: 'host6', full_name: 'Grace Tan', avatar_url: null, qr_payment_url: null, qr_payment_label: null, is_verified: true, is_host: true, host_rating: 4.8, host_review_count: 17, response_time_hours: 1, bio: null, city: null, notify_new_booking: true, notify_messages: true, notify_reminders: true, notify_promos: false, created_at: '2023-10-01' },
  },
  {
    id: '7',
    host_id: 'host7',
    category: 'mirrorless',
    brand: 'Nikon',
    model: 'Z8',
    title: 'Nikon Z8 Full-Frame Mirrorless Camera',
    description: '45.7MP stacked BSI sensor, 8K RAW video, no blackout shooting at 20fps.',
    condition: 'mint',
    daily_price: 3200,
    weekly_price: 19000,
    monthly_price: 62000,
    security_deposit: 14000,
    delivery_fee: null,
    city: 'Makati',
    province: 'Metro Manila',
    is_instant_book: true,
    is_active: true,
    is_draft: false,
    rating: 4.97,
    review_count: 41, view_count: 0,
    images: ['https://images.unsplash.com/photo-1614108830714-74f0e4c8cd7e?w=800&q=80'],
    accessories: ['Battery x2', 'Charger', 'USB-C Cable', 'Strap'],
    created_at: '2024-02-01',
    host: { id: 'host7', full_name: 'James Ong', avatar_url: null, qr_payment_url: null, qr_payment_label: null, is_verified: true, is_host: true, host_rating: 5.0, host_review_count: 36, response_time_hours: 1, bio: null, city: null, notify_new_booking: true, notify_messages: true, notify_reminders: true, notify_promos: false, created_at: '2023-03-01' },
  },
  {
    id: '8',
    host_id: 'host8',
    category: 'mirrorless',
    brand: 'Fujifilm',
    model: 'X-T5',
    title: 'Fujifilm X-T5 Mirrorless Camera',
    description: '40MP APS-C sensor with iconic film simulation modes. Perfect for travel and street photography.',
    condition: 'excellent',
    daily_price: 1800,
    weekly_price: 10500,
    monthly_price: 36000,
    security_deposit: 8000,
    delivery_fee: null,
    city: 'Davao City',
    province: 'Davao del Sur',
    is_instant_book: true,
    is_active: true,
    is_draft: false,
    rating: 4.96,
    review_count: 53, view_count: 0,
    images: ['https://images.unsplash.com/photo-1749016888524-967635aa2c6f?w=800&q=80'],
    accessories: ['Battery x2', 'Charger', 'SD Card 128GB', 'Strap'],
    created_at: '2024-02-05',
    host: { id: 'host8', full_name: 'Sofia Mendoza', avatar_url: null, qr_payment_url: null, qr_payment_label: null, is_verified: true, is_host: true, host_rating: 4.9, host_review_count: 48, response_time_hours: 2, bio: null, city: null, notify_new_booking: true, notify_messages: true, notify_reminders: true, notify_promos: false, created_at: '2023-04-01' },
  },
  {
    id: '9',
    host_id: 'host9',
    category: 'mirrorless',
    brand: 'Sony',
    model: 'A7C II',
    title: 'Sony A7C II Compact Full-Frame Camera',
    description: 'Ultra-compact full-frame with AI autofocus. Great for travel vlogging and content creation.',
    condition: 'excellent',
    daily_price: 2000,
    weekly_price: 12000,
    monthly_price: 40000,
    security_deposit: 9000,
    delivery_fee: null,
    city: 'Quezon City',
    province: 'Metro Manila',
    is_instant_book: true,
    is_active: true,
    is_draft: false,
    rating: 4.94,
    review_count: 29, view_count: 0,
    images: ['https://images.unsplash.com/photo-1552233706-c3ff6a3da279?w=800&q=80'],
    accessories: ['Battery x2', 'Charger', 'USB-C Cable', 'Strap'],
    created_at: '2024-02-10',
    host: { id: 'host9', full_name: 'Ben Aguilar', avatar_url: null, qr_payment_url: null, qr_payment_label: null, is_verified: true, is_host: true, host_rating: 4.8, host_review_count: 22, response_time_hours: 3, bio: null, city: null, notify_new_booking: true, notify_messages: true, notify_reminders: true, notify_promos: false, created_at: '2023-08-01' },
  },
  {
    id: '10',
    host_id: 'host10',
    category: 'mirrorless',
    brand: 'Canon',
    model: 'EOS R5',
    title: 'Canon EOS R5 Full-Frame Mirrorless',
    description: '45MP sensor, 8K RAW video, IBIS — the ultimate hybrid shooter camera.',
    condition: 'excellent',
    daily_price: 3500,
    weekly_price: 21000,
    monthly_price: 70000,
    security_deposit: 16000,
    delivery_fee: null,
    city: 'BGC',
    province: 'Metro Manila',
    is_instant_book: false,
    is_active: true,
    is_draft: false,
    rating: 4.99,
    review_count: 76, view_count: 0,
    images: ['https://images.unsplash.com/photo-1641770058653-6ba80f9b7ebc?w=800&q=80'],
    accessories: ['Battery x3', 'Charger', 'CF Express Card', 'Strap'],
    created_at: '2024-02-15',
    host: { id: 'host10', full_name: 'Trisha Gomez', avatar_url: null, qr_payment_url: null, qr_payment_label: null, is_verified: true, is_host: true, host_rating: 5.0, host_review_count: 61, response_time_hours: 1, bio: null, city: null, notify_new_booking: true, notify_messages: true, notify_reminders: true, notify_promos: false, created_at: '2023-02-01' },
  },
  {
    id: '11',
    host_id: 'host11',
    category: 'smartphone',
    brand: 'Apple',
    model: 'iPhone 15 Pro',
    title: 'iPhone 15 Pro — 256GB Natural Titanium',
    description: 'ProRAW, 4K ProRes video, 48MP main camera. Ideal for mobile filmmaking.',
    condition: 'excellent',
    daily_price: 950,
    weekly_price: 5500,
    monthly_price: 19000,
    security_deposit: 4000,
    delivery_fee: null,
    city: 'Manila',
    province: 'Metro Manila',
    is_instant_book: true,
    is_active: true,
    is_draft: false,
    rating: 4.91,
    review_count: 47, view_count: 0,
    images: ['https://images.unsplash.com/photo-1718223483120-8131e57f948b?w=800&q=80'],
    accessories: ['USB-C Cable', 'MagSafe Charger', 'Case'],
    created_at: '2024-02-20',
    host: { id: 'host11', full_name: 'Nina Reyes', avatar_url: null, qr_payment_url: null, qr_payment_label: null, is_verified: true, is_host: true, host_rating: 4.9, host_review_count: 38, response_time_hours: 2, bio: null, city: null, notify_new_booking: true, notify_messages: true, notify_reminders: true, notify_promos: false, created_at: '2023-11-01' },
  },
  {
    id: '12',
    host_id: 'host12',
    category: 'smartphone',
    brand: 'Google',
    model: 'Pixel 9 Pro',
    title: 'Google Pixel 9 Pro — 256GB',
    description: 'Computational photography king — Night Sight, Magic Eraser, Best Take, and 50MP triple camera.',
    condition: 'mint',
    daily_price: 900,
    weekly_price: 5200,
    monthly_price: 18000,
    security_deposit: 4000,
    delivery_fee: null,
    city: 'Cebu City',
    province: 'Cebu',
    is_instant_book: true,
    is_active: true,
    is_draft: false,
    rating: 4.89,
    review_count: 18, view_count: 0,
    images: ['https://images.unsplash.com/photo-1756517313520-c6c25364ce65?w=800&q=80'],
    accessories: ['USB-C Cable', 'Charger', 'Case'],
    created_at: '2024-03-01',
    host: { id: 'host12', full_name: 'Andrei Flores', avatar_url: null, qr_payment_url: null, qr_payment_label: null, is_verified: false, is_host: true, host_rating: 4.7, host_review_count: 14, response_time_hours: 4, bio: null, city: null, notify_new_booking: true, notify_messages: true, notify_reminders: true, notify_promos: false, created_at: '2023-12-01' },
  },
  {
    id: '13',
    host_id: 'host13',
    category: 'smartphone',
    brand: 'Samsung',
    model: 'Galaxy Z Fold 6',
    title: 'Samsung Galaxy Z Fold 6 — 512GB',
    description: 'Foldable powerhouse with 50MP triple camera. Unique for content monitoring and creative angles.',
    condition: 'mint',
    daily_price: 1400,
    weekly_price: 8200,
    monthly_price: 28000,
    security_deposit: 6000,
    delivery_fee: null,
    city: 'Pasig',
    province: 'Metro Manila',
    is_instant_book: true,
    is_active: true,
    is_draft: false,
    rating: 4.85,
    review_count: 11, view_count: 0,
    images: ['https://images.unsplash.com/photo-1784969314879-4d9a260e98e6?w=800&q=80'],
    accessories: ['USB-C Cable', 'S Pen', 'Case', 'Charger'],
    created_at: '2024-03-05',
    host: { id: 'host13', full_name: 'Maricel Santos', avatar_url: null, qr_payment_url: null, qr_payment_label: null, is_verified: true, is_host: true, host_rating: 4.8, host_review_count: 9, response_time_hours: 2, bio: null, city: null, notify_new_booking: true, notify_messages: true, notify_reminders: true, notify_promos: false, created_at: '2024-01-01' },
  },
  {
    id: '14',
    host_id: 'host14',
    category: 'mirrorless',
    brand: 'OM System',
    model: 'OM-1 Mark II',
    title: 'OM System OM-1 Mark II Mirrorless',
    description: 'IP53 weather-sealed, 120fps burst, AI subject detection. Built for outdoor and action photography.',
    condition: 'excellent',
    daily_price: 1600,
    weekly_price: 9500,
    monthly_price: 32000,
    security_deposit: 7000,
    delivery_fee: null,
    city: 'Davao City',
    province: 'Davao del Sur',
    is_instant_book: false,
    is_active: true,
    is_draft: false,
    rating: 4.90,
    review_count: 23, view_count: 0,
    images: ['https://images.unsplash.com/photo-1542038784456-1ea8e935640e?w=800&q=80'],
    accessories: ['Battery x2', 'Charger', 'USB-C Cable', 'Strap'],
    created_at: '2024-03-10',
    host: { id: 'host14', full_name: 'Diego Ramos', avatar_url: null, qr_payment_url: null, qr_payment_label: null, is_verified: true, is_host: true, host_rating: 4.9, host_review_count: 19, response_time_hours: 3, bio: null, city: null, notify_new_booking: true, notify_messages: true, notify_reminders: true, notify_promos: false, created_at: '2023-06-15' },
  },
  {
    id: '15',
    host_id: 'host15',
    category: 'smartphone',
    brand: 'Apple',
    model: 'iPhone 16 Pro',
    title: 'iPhone 16 Pro — 512GB Black Titanium',
    description: 'Camera Control button, 5x optical zoom, 4K120 ProRes. The filmmaker\'s iPhone.',
    condition: 'mint',
    daily_price: 1100,
    weekly_price: 6500,
    monthly_price: 22000,
    security_deposit: 5000,
    delivery_fee: null,
    city: 'Mandaluyong',
    province: 'Metro Manila',
    is_instant_book: true,
    is_active: true,
    is_draft: false,
    rating: 4.97,
    review_count: 34, view_count: 0,
    images: ['https://images.unsplash.com/photo-1592750475338-74b7b21085ab?w=800&q=80'],
    accessories: ['USB-C Cable', 'MagSafe Charger', 'Case', 'Screen Protector'],
    created_at: '2024-03-15',
    host: { id: 'host15', full_name: 'Camille Bautista', avatar_url: null, qr_payment_url: null, qr_payment_label: null, is_verified: true, is_host: true, host_rating: 5.0, host_review_count: 27, response_time_hours: 1, bio: null, city: null, notify_new_booking: true, notify_messages: true, notify_reminders: true, notify_promos: false, created_at: '2023-07-20' },
  },
  {
    id: '16',
    host_id: 'host16',
    category: 'cinema',
    brand: 'Blackmagic',
    model: 'Pocket Cinema Camera 6K Pro',
    title: 'Blackmagic Pocket Cinema Camera 6K Pro',
    description: '6K Super 35 sensor, 13 stops of dynamic range, built-in ND filters. Cinema-grade for indie productions.',
    condition: 'excellent',
    daily_price: 3800,
    weekly_price: 22000,
    monthly_price: 75000,
    security_deposit: 18000,
    delivery_fee: null,
    city: 'Manila',
    province: 'Metro Manila',
    is_instant_book: false,
    is_active: true,
    is_draft: false,
    rating: 4.92,
    review_count: 16, view_count: 0,
    images: ['https://images.unsplash.com/photo-1543235074-4768b5c2233c?w=800&q=80'],
    accessories: ['Battery x3', 'CFast Card', 'HDMI Cable', 'Battery Grip'],
    created_at: '2024-03-20',
    host: { id: 'host16', full_name: 'Marco Dela Cruz', avatar_url: null, qr_payment_url: null, qr_payment_label: null, is_verified: true, is_host: true, host_rating: 4.9, host_review_count: 13, response_time_hours: 2, bio: null, city: null, notify_new_booking: true, notify_messages: true, notify_reminders: true, notify_promos: false, created_at: '2023-09-10' },
  },
]

export const MOCK_BUNDLES = [
  {
    id: 'b1',
    title: 'Vlogging Kit',
    items: ['Sony ZV-E10', 'Wireless Microphone', 'Tripod', 'LED Light'],
    daily_price: 1800,
    image: 'https://images.unsplash.com/photo-1516035069371-29a1b244cc32?w=800&q=80',
  },
  {
    id: 'b2',
    title: 'Wedding Photography Kit',
    items: ['Sony A7 IV', '85mm f/1.4 Lens', 'Flash x2', 'Extra Batteries'],
    daily_price: 5500,
    image: 'https://images.unsplash.com/photo-1606216794074-735e91aa2c92?w=800&q=80',
  },
  {
    id: 'b3',
    title: 'Travel Content Kit',
    items: ['Fujifilm X100VI', 'ND Filter Set', 'Gorilla Pod', 'Memory Cards'],
    daily_price: 2200,
    image: 'https://images.unsplash.com/photo-1692895591954-451050db22fd?w=800&q=80',
  },
]
